# Generated by Django 4.2.1 on 2023-05-20 12:31

import api_v1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_idea_voting_end_idea_voting_result_idea_voting_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='idea',
            name='order',
            field=models.PositiveIntegerField(default=api_v1.models.get_next_order_value),
        ),
    ]
